---
output: html_document
editor_options: 
  chunk_output_type: console
---
1) Load Libraries and Shapefile
```{r Libraries}

library(plyr)
library(dplyr)
library(tigris)
library(maptools)
library(maps)
library(mapdata)
library(sp)
library(ggplot2)
library(ggmap)
library(rgdal)
library(sf)
library(leaflet)

municipios <- readOGR("GIS/ICF downloads/m1103va002001_hn.shp")



```

2) Presidente 2005

```{r Presidente 2005 }

# Import Data

presidente2005 <- read.csv ("Elecciones/data/2005/resultados_presidente_2005_por_municipio.csv", stringsAsFactors = FALSE)

# Dejar solo los partidos para encontrar el ganador
presidente2005.parties <- select(presidente2005, PINU, PN, PL, UD, DC)

# Encontrar el ganador
winners2005 <- as.data.frame(cbind
                         (row.names(presidente2005.parties),
                           apply(presidente2005.parties, 1, 
                                 function(x) names(presidente2005.parties)[which(x==max(x))]))) 

# Consolidar la dataframe entre estadisticas y ganadores

p2005 <- cbind (presidente2005, winners2005$V2)
p2005$ganador <- p2005$`winners2005$V2`
p2005$`winners2005$V2` <- NULL

# Determine Color Palette

p2005$colorpartido <- 
  ifelse(p2005$ganador == "PN", 
         yes = "dodgerblue3", no = "firebrick3")

#Limpiar Ambiente

rm(presidente2005, presidente2005.parties, winners2005)


```

3) Map Presidente 2005

```{r}

# Merge shapefile with data

mun.merge2005 <- 
  geo_join(spatial_data = municipios,
           data_frame = p2005,
           by_sp = "nombre",
           by_df = "Municipio",
           how = "left")

##### Do the Plot ###

sp::plot(mun.merge2005, 
     col = mun.merge2005$colorpartido,
     border = "white",
     lwd = 1.75, lty = 1,
     main = "Resultados Presidente: Elecciones 2005", cex.main = 2
     )



```




2) Presidente 2009

```{r Presidente 2009 }
presidente2009 <- read.csv ("Elecciones/data/2009/resultados_presidente_2009_por_municipio.csv", stringsAsFactors = FALSE)

# Dejar solo los partidos para encontrar el ganador
presidente2009.parties <- select(presidente2009, PN, PINU, DC, PL, UD)

# Encontrar el ganador
winners2009 <- as.data.frame(cbind
                         (row.names(presidente2009.parties),
                           apply(presidente2009.parties, 1, 
                                 function(x) names(presidente2009.parties)[which(x==max(x))]))) 

# Consolidar la dataframe entre estadisticas y ganadores

p2009 <- cbind (presidente2009, winners2009$V2)
p2009$ganador <- p2009$`winners2009$V2`
p2009$`winners2009$V2` <- NULL

# Determine Color Palette

p2009$colorpartido <- 
  ifelse(p2009$ganador == "PN", 
         yes = "dodgerblue3", no = "firebrick3")

#Limpiar Ambiente

rm(presidente2009, presidente2009.parties, winners2009)


```

3) Map Presidente 2009

```{r}

# Merge shapefile with data

mun.merge2009 <- 
  geo_join(spatial_data = municipios,
           data_frame = p2009,
           by_sp = "nombre",
           by_df = "Municipio",
           how = "left")

##### Do the Plot ###

sp::plot(mun.merge2009, 
     col = mun.merge2009$colorpartido,
     border = "white",
     lwd = 1.75, lty = 1,
     main = "Resultados Presidente: Elecciones 2009", cex.main = 2
     )



```

4) Presidente 2013

```{r Presidente 2013 }

presidente2013 <- read.csv ("Elecciones/data/2013/resultados_presidente_2013_por_municipio.csv", stringsAsFactors = FALSE)

# Dejar solo los partidos para encontrar el ganador
presidente2013.parties <- select(presidente2013, DC, APH, PL, PAC, LIBRE, FAPER, PINU, PN)

# Encontrar el ganador
winners2013 <- as.data.frame(cbind
                         (row.names(presidente2013.parties),
                           apply(presidente2013.parties, 1, 
                                 function(x) names(presidente2013.parties)[which(x==max(x))]))) 

# Consolidar la dataframe entre estadisticas y ganadores

p2013 <- cbind (presidente2013, winners2013$V2)
p2013$ganador <- p2013$`winners2013$V2`
p2013$`winners2013$V2` <- NULL

p2013$colorpartido <- "gray80"

p2013$colorpartido <- 
  ifelse(p2013$ganador == "PN", 
         yes = "dodgerblue3", no = p2013$colorpartido)

p2013$colorpartido <- 
  ifelse(p2013$ganador == "PL", 
         yes = "firebrick3", no = p2013$colorpartido)

p2013$colorpartido <- 
  ifelse(p2013$ganador == "LIBRE", 
         yes = "black", no = p2013$colorpartido)

p2013$colorpartido <- 
  ifelse(p2013$ganador == "PAC", 
         yes = "goldenrod", no = p2013$colorpartido)


#Limpiar Ambiente

rm(presidente2013, presidente2013.parties, winners2013)

```

5) Map Presidente 2013

```{r}

# Merge shapefile with data

mun.merge2013 <- 
  geo_join(spatial_data = municipios,
           data_frame = p2013,
           by_sp = "nombre",
           by_df = "Municipio",
           how = "left")

##### Do the Plot ###

sp::plot(mun.merge2013, 
     col = mun.merge2013$colorpartido,
     border = "white",
     lwd = 1.75, lty = 1,
     main = "Resultados Presidente: Elecciones 2013", cex.main = 2
     )



```

6) Presidente 2017

```{r Presidente 2017}

presidente2017 <- read.csv ("Elecciones/data/2017/resultados_presidente_2017_por_municipio.csv", stringsAsFactors = FALSE)


# Dejar solo los partidos para encontrar el ganador
presidente2017.parties <- select(presidente2017, PL, PN, Alianza, DC, UD, PAC, APH, FA, VAMOS)

# Encontrar el ganador
winners2017 <- as.data.frame(cbind
                         (row.names(presidente2017.parties),
                           apply(presidente2017.parties, 1, 
                                 function(x) names(presidente2017.parties)[which(x==max(x))]))) 

# Consolidar la dataframe entre estadisticas y ganadores

p2017 <- cbind (presidente2017, winners2017$V2)
p2017$ganador <- p2017$`winners2017$V2`
p2017$`winners2017$V2` <- NULL


### Definir colores de partidos ###
p2017$colorpartido <- "gray80"

p2017$colorpartido <- 
  ifelse(p2017$ganador == "PN", 
         yes = "dodgerblue3", no = p2017$colorpartido)

p2017$colorpartido <- 
  ifelse(p2017$ganador == "PL", 
         yes = "firebrick3", no = p2017$colorpartido)

p2017$colorpartido <- 
  ifelse(p2017$ganador == "Alianza", 
         yes = "black", no = p2017$colorpartido)

#Limpiar Ambiente

rm(presidente2017, presidente2017.parties, winners2017)
```

8) Map Presidente 2017

```{r}

# Merge shapefile with data

mun.merge2017 <- 
  geo_join(spatial_data = municipios,
           data_frame = p2017,
           by_sp = "nombre",
           by_df = "Municipio",
           how = "left")

##### Do the Plot ###


sp::plot(mun.merge2017, 
     col = mun.merge2017$colorpartido,
     border = "white",
     lwd = 1.75, lty = 1,
     main = "Resultados Presidente: Elecciones 2017", cex.main = 2
     )



```

































